### ISSUE TITLE
Old use of force fields have been removed

### ISSUE THREAD

**Issue by huy-d-nguyen** [ppact/processing#292]
Hi @ayyubibrahimi, could you bring back those fields below to the three new `use-of-forces` tables?
`force_description`, `force_reason`, `citizen_involvement` ,` citizen_age`, `traffic_stop `

Thanks

**Comment by ayyubibrahimi** [comment]
These changes are being addressed in pr #293. Khoi will review. 

@huy-d-nguyen these three tables are derived from an updated `use_of_force` table that we received from the New Orleans Police Department. The new table did not have the fields `citizen_involvement` or `traffic stop` like the old version, therefore only `use_of_force_description`, `use_of_force_reason`, and `citizen_age` have been added to all three `use_of_force` tables. 

Also, please note that `force_description` and `force_reason` have been renamed to `use_of_force_description` and `use_of_force_reason`

**Comment by pckhoi** [comment]
@huy-d-nguyen do you want the `use_of_force_description`, `use_of_force_reason`, and `citizen_age` repeated across 3 tables?

**Comment by huy-d-nguyen** [comment]
@pckhoi , I think we do not need the duplication across the 3 tables. But since the old UI use the fields I listed above, so please discuss with Jeeves and then give us the sense for using new data, thank you.

**Comment by pckhoi** [comment]
@huy-d-nguyen I would like to put the description and reason fields in the main use-of-force table. And put the citizen age field in the citizen table. And those will be the only places where you can find these fields. No duplication.

And I'm simply coming from a data normalization perspective. How to make the data as normalized as possible.

@rajivsinclair does that sound fine to you? Please make the final call.

**Comment by rajivsinclair** [comment]
Thanks @pckhoi. This structure seems fine to me too, if the `description` and `reason` fields are always the same across all officers on a single use_of_force report? 

@ayyubibrahimi, can you please confirm why the `citizen_involvement`, `citizen_age`, `citizen_race`, `traffic_stop` fields are no longer available in the use of force data?

Even if these fields are sometimes missing, we should try to fill them for those cases where the input data is available.

**Comment by ayyubibrahimi** [comment]
`citizen_race` and `citizen_age` are still present in the `use_of_force` table.

 `citizen_involvement` and `traffic_stop` were fields included in the old `new_orleans_pd_uof` table that we received from the IPM, which we have since replaced with the `new_orleans_pd_uof` table that we received directly from NOPD.

An analogous field to the old `traffic_stop` field can be found in the new `new_orleans_pd_uof` table,`service_type` which includes the options: `traffic stop`, `call for service`, `arresting`, `other`, `pedestrian stop`, `serving a warrant`, `transport`,  `arresting; call for service`

It is likely that both tables can be merged on `tracking_id` if we are interested in extracting `citizen_involvement`

**Comment by pckhoi** [comment]
@rajivsinclair yes, the reason and the description fields are unique per use of force record. They are merely replicated onto other tables.

**Comment by rajivsinclair** [comment]
Got it . Thanks for confirming.

**Comment by ayyubibrahimi** [comment]
@pckhoi can you confirm the final solution?

**Comment by pckhoi** [comment]
The most important thing is that we always follow a few principles when processing data. One of the principles we should follow here is making the data as normalized as possible. That means all columns should end up in exactly one table only, except for those that are foreign key to other tables. Doing that allow the data to remain useful to as many purposes as possible while leaving less room for confusion.

Let's keep the `use_of_force_description`, `use_of_force_reason` in the `use-of-force` table.

`citizen_age` should be in the citizens table of course.

@ayyubibrahimi please go ahead and make the above changes

`traffic_stop` field is gone but `service_type` definitely feels like a much better alternative. Let's keep the `service_type` column.

`citizen_involvement` is missing but we can try include it like Ayyub pointed out. @rajivsinclair if you really want to keep that field then please open another issue as this issue is very crammed already.

@huy-d-nguyen I believe that answered all of your questions.

**Comment by ayyubibrahimi** [comment]
Sounds good. 

FYI - `use_of_force_description` was kept in the `uof_officers` table. I will limit it to that table, `use_of_force_reason` will be limited to the `use_of_force` table and `citizen_age` will be limited to the `uof_citizens` table.

**Comment by pckhoi** [comment]
Sounds good to me.

**Comment by ayyubibrahimi** [comment]
@huy-d-nguyen these issues were just resolved in pr #293. Please let me know if there are any issues

**Comment by huy-d-nguyen** [comment]
@ayyubibrahimi thank you for letting me know. We will continue our data importing task next week and will tell you if we have any other issues.

**Comment by huy-d-nguyen** [comment]
Hi @ayyubibrahimi, you've mentioned that `citizen_race` is still present, but I do not see it in `use_of_force` table. Could you confirm this? Thanks

**Comment by ayyubibrahimi** [comment]
Hi @huy-d-nguyen - sorry for the lack of clarity. What I meant is that `citizen_race` is still in existence, unlike `citizen_involvement` and `traffic_stop`. 

As Khoi requested, `citizen_race` is only present in the `uof_citizens` table, one of three use of force table tables that exist: `use_of_force`, `uof_officers`, and `uof_citizens`

**Comment by huy-d-nguyen** [comment]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/60863227/170471979-d6746222-2cbd-4fc2-b66e-c61712573734.png">
Look like the `uof-citizens` does not include the `citizen_race` column. Can you help us to check it again?

**Comment by ayyubibrahimi** [comment]
Please check again.

**Comment by huy-d-nguyen** [comment]
Thank you @ayyubibrahimi! Could you tell us why you replace `use_of_force_type` by `use_of_force_description` in `use-of-force-officers` table? Also, I don't see any differences between the new `use_of_force_description` and `use_of_force_type` in the commit `ecc4a8494dc5700f3bbe590b9b58642e`. 
cc @rajivsinclair

**Comment by ayyubibrahimi** [comment]
Yes. I came to the realization that `use_of_force_description` is a more accurate field name when compared to `use_of_force_type`. There is no change except for the name. If the change introduces a hassle, I'm happy to revert the field name to `use_of_force_type`.
